services:
  - type: web
    name: questionpaper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.1
